language: python

dist: precise

python:
  - "2.7"
sudo: required

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y ffmpeg

install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
  - pip install codecov

script: video_worker

script:
  - python tests/test_api_connect.py
  - python tests/test_build.py
  - make validate

after_success:
  - pip install -U codecov
  - codecov
