---

# ---
# AWS
# ---
veda_s3_hotstore_bucket:
veda_deliverable_bucket:
edx_s3_endpoint_bucket:
aws_video_images_bucket:
aws_video_images_prefix: ''

# ---
# Celery
# ---
celery_threads: 1

# ---
# VAL user creds
# ---
val_api_url:
val_video_images_url:
val_client_id:
val_password:
val_secret_key:
val_token_url:
val_username:

## VEDA API Auth
veda_api_url:
veda_auth_url:
veda_client_id:
veda_secret_key:
veda_token_url:

## CLOUD
rabbitmq_broker: ""
rabbitmq_pass: ""
rabbitmq_user: ""
