---
## NOTE!
# NEVER COMMIT A SECRET HERE!
#
# This file is meant as a guide, but should not be assumed to deploy to production.
# To deploy changes to this file to production,
# change in @edx/veda-secure/shared/instance_config.yaml
#
#

celery_threads: 1
# ----------
onsite_worker: False
veda_s3_hotstore_bucket: ""
##---
# This is a list of encodes and their respective course
# boolean matches
encode_dict:
    review_proc:
        - review
    mobile_override:
        - override
    s3_proc:
        - mobile_low
        - audio_mp3
        - desktop_mp4
        - hls

    yt_proc:
        - youtube

##---
# This is a list of encode profiles and their val profile matches
# boolean matches
val_profile_dict:
    mobile_low:
        - mobile_low

    desktop_mp4:
        - desktop_mp4

    override:
        - desktop_mp4
        - mobile_low

    audio_mp3:
        - audio_mp3

    youtube:
        - youtube
    review:
    hls:
        - hls


#--
# Global settings
heal_start: 3
heal_end: 144
global_timeout: 40
ffmpeg_compiled: 'ffmpeg'
ffprobe_compiled: 'ffprobe'

...
